### ISSUE TITLE
720p and 480p are not being tagged as HD

### ISSUE THREAD

**Issue by angelxmoreno** [Ivshti/video-name-parser#2]
I see where the issue is too. I can send a PR if you agree that they should be tagged as HD

**Comment by Ivshti** [comment]
480p is definitely not HD, but 720p can be considered HD when all the other options are 480p.

Since we can't know this in that module, I disagree that we should make 720p == hd

IMO hd tag should be removed entirely, because it's ambiguous, but it's kept for legacy reasons currently

**Comment by angelxmoreno** [comment]
hhmm, got it. thanks for clearing that up! BTW, thanks for the lib. I am using it in a desktop app.

**Comment by Ivshti** [comment]
@angelxmoreno can't wait to see what you've done!
